# Site Settings
locale                   : "en-UK"
name                     : &name "Ali Hariri"
title: Ali Hariri
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://haririali.gitlab.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed

include: [_pages]

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
